"""Add transaction category foreign key

Revision ID: 7997f9891a3f
Revises: a92f5f7b3bd2
Create Date: 2026-09-06 16:52:50.870232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7997f9891a3f'
down_revision = 'a92f5f7b3bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_transactions_category_id_categories',
            'categories',
            ['category_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_transactions_category_id_categories',
            type_='foreignkey'
        )

    # ### end Alembic commands ###
